name: Ruby 3.1 on Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.1']
        in_tail: [true, false]
        os:
          - windows-latest
        experimental: [false]

    name: in_tail ${{ matrix.in_tail }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: ridk exec bundle install
      - name: test in_tail
        if: ${{ matrix.in_tail }}
        run: bundle exec rake test TESTOPTS=-v TEST=test/plugin/test_in_tail.rb
      - name: test without in_tail
        if: ${{ !matrix.in_tail }}
        run: |
          rm test/plugin/test_in_tail.rb
          bundle exec rake test TESTOPTS=-v
